### ISSUE TITLE
Version 1.5.1 not deployed to maven central

### ISSUE THREAD

**Issue by nytro77** [eclipse-ee4j/metro-saaj#114]
I cannot find version 1.5.1 in maven central.

The latest version there is 1.5.0

**Comment by lukasj** [comment]
1.5.1 is available in OSS sonatype staging only for now

**Comment by deki** [comment]
now that SAAJ API has been published to central, it would be nice to also have the implementation...

**Comment by Tomas-Kraus** [comment]
Releasing SAAJ RI into central:
- Release job: https://jenkins.eclipse.org/metro/job/nexus-staging/44/console
- Merging release info into EE4J_8 branch: https://github.com/eclipse-ee4j/metro-saaj/pull/115
