### ISSUE TITLE
document existing system properties recognized by implementation

### ISSUE THREAD

**Issue by lukasj** [eclipse-ee4j/metro-saaj#121]

**Comment by runeflobakk** [comment]
`com.sun.xml.messaging.saaj.soap.saxParserPoolSize`

Allows to specify another value for the size of the parser pool used for SAX-parsing. The default when not specified is `5`, but applications with high load and/or concurrency may benefit from setting this to a higher value.

Issue: https://github.com/eclipse-ee4j/metro-saaj/issues/73

**Comment by runeflobakk** [comment]
`saaj.mime.soapBodyPartSizeLimit`

Used to specify the max amount in bytes a SOAP body part is allowed to contain. This property can (should) be used to protect against maliciously crafted requests which can take down the server with OutOfMemoryError.

Pull-request: https://github.com/eclipse-ee4j/metro-saaj/pull/117
