### ISSUE TITLE
Release 1.5.2 to maven central

### ISSUE THREAD

**Issue by tobias-bahls** [eclipse-ee4j/metro-saaj#125]
Hi,

we currently face the bug fixed by https://github.com/eclipse-ee4j/metro-saaj/commit/bcb3cd85a6ece791a3db524c07d31401e5dcf7ec in our system.

We used 1.5.2 with the fix from Sonatype Staging, hoping that it will eventually get released to Maven Central. But now 1.5.2 is completely gone from Sonatype Staging.

Is there any chance to get 1.5.2 released to Maven Central?

Thanks,
Tobias

**Comment by lukasj** [comment]
there is 1.5.2-b01 in central which should contain the fix you need
