### ISSUE TITLE
Need an API to set socket timeout for URLConnection that SAAJ uses

### ISSUE THREAD

**Issue by Tomas-Kraus** [eclipse-ee4j/metro-saaj#70]
SAAJ uses URLConnection internally to make SOAP call. There is no way to set timeout for connection.call. This result is locked thread for over 10 mins.

From JDK 1.5 onwards URLConnection support setting of timeout for socket connection.

SAAJ lib should implement this timeout and provide an API to set the value of timeout.
#### Environment
linux
#### Affected Versions
[1.3]

**Comment by lukasj** [comment]
added `saaj.connect.timeout` and `saaj.read.timeout` system wide properties
