### ISSUE TITLE
Specially crafted SWA request can take down server with OOM

### ISSUE THREAD

**Issue by Tomas-Kraus** [eclipse-ee4j/metro-saaj#77]
Currently there is no protection against malicious SWA requests where the SOAP part of the request is specially crafted to consume as much memory as possible on the server (in the XML parser). This might lead to OOM and system unavailability. We have created a fix (lets you set max size of body part) that can be found here: [https://github.com/digipost/saaj/commit/1e65b801508e6be12ece76120dd00ad04022f4c0](https://github.com/digipost/saaj/commit/1e65b801508e6be12ece76120dd00ad04022f4c0)
#### Affected Versions
[current]

**Comment by lukasj** [comment]
I believe this is covered by #117
