### ISSUE TITLE
Requesting a fault reason text in another Locale returns null

### ISSUE THREAD

**Issue by Tomas-Kraus** [eclipse-ee4j/metro-saaj#78]
While consuming a wcf web service which uses RM and username security, I can make a call no problem but when receiving a fault, I cannot extract the reason text in the different locales which are received. Dumping the received messages to the console clearly shows the reason text in multiple languages using xml:lang="fr" and xml:lang="en".

Even enumeration of the reason text locales and more doesn't work.

Is this a bug or is there something I have to do to enable locales.

I am a java newbie.
#### Environment
metro 2.3.1
#### Affected Versions
[1.3.16]

**Comment by lukasj** [comment]
I cannot reproduce this and a [test](https://github.com/eclipse-ee4j/metro-saaj/blob/master/saaj-ri/src/test/java/soap12/SOAPFaultTests.java#L31) for this API works fine. Looking at the actual fault, it is not valid since Subcode cannot contain another Subcode.
