### ISSUE TITLE
Build CI/CD pipeline

### ISSUE THREAD

**Issue by m0mus** [eclipse-ee4j/metro-saaj#96]
This task is for creating a basic build CI/CD pipeline for this project on Eclipse infrastructure. More information is here: https://ci.eclipse.org/.

**Comment by Tomas-Kraus** [comment]
Jobs:
- master: https://jenkins.eclipse.org/metro/job/saaj-ri-master-build/
- EE4J_8: https://jenkins.eclipse.org/metro/job/saaj-ri-ee4j8-build/

Build is failing in jUnit tests. It looks like some docker image environment issue.

**Comment by m0mus** [comment]
The job itself is done, so closing this task. Please create a new one for fixing JUnit tests.
